name: requirements-project
on:
  pull_request:
    branches:
      - staging
      - master
  workflow_dispatch:

jobs:
  requirements:
    uses: MartianFlow/java-screenplay-browserstack-framework/.github/workflows/requirements_frontend.yml@v1
    with:
      project-name: ${{ github.event.repository.name }}
      project-key: ${{ github.event.repository.name }}
      language: java
      sonar-project-properties-file: 'sonar-project-custom.properties'
    secrets: inherit