name: test-integration-workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  integration-e2e-tests:
    uses: ./.github/workflows/test_frontend_integration_pipeline.yml
    secrets:
      DIG_READER_GITHUB_ACCESS_TOKEN: ${{ secrets.DIG_READER_GITHUB_ACCESS_TOKEN }}
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    with:
      command-install:  |
        sed -i "s/@browserstack.user@/${{ secrets.BROWSERSTACK_USERNAME }}/g" serenity.properties &&
        sed -i "s/@browserstack.key@/${{ secrets.BROWSERSTACK_ACCESS_KEY }}/g" serenity.properties &&
        sed -i "s/@browserstack.user@/${{ secrets.BROWSERSTACK_USERNAME }}/g" browserstack.yml &&
        sed -i "s/@browserstack.key@/${{ secrets.BROWSERSTACK_ACCESS_KEY }}/g" browserstack.yml
      command-execute: 'mvn clean verify 
                        -D"environment=remote" 
                        -P"sample-test" 
                        '
      files-to-export: >
        target/site/serenity/serenity-summary.html
        target/logback-reports/logback-execution-report.txt
      prefix-team: 'automation-test-martianFlow'
      debug: false
      environment: 'main'
      path-report-file: 'target/serenity-reports/cucumber_report.json'
      repository: 'java-screenplay-browserstack-framework'
      target-url-zap: 'https://the-internet.herokuapp.com/'
      name-file-report: results.csv