name: test-integration-workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update files with BrowserStack credentials
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        run: |
          echo 'Updating BrowserStack credentials in serenity.properties and browserstack.yml'
          sed -i 's/@buser@/'"$BROWSERSTACK_USERNAME"'/' serenity.properties
          sed -i 's/@bkey@/'"$BROWSERSTACK_ACCESS_KEY"'/' serenity.properties
          sed -i 's/@browserstack.user@/'"$BROWSERSTACK_USERNAME"'/' browserstack.yml
          sed -i 's/@browserstack.key@/'"$BROWSERSTACK_ACCESS_KEY"'/' browserstack.yml

      - name: Upload updated files
        uses: actions/upload-artifact@v3
        with:
          name: updated-config-files
          path: |
            serenity.properties
            browserstack.yml

  integration-e2e-tests:
    needs: update-files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download updated files
        uses: actions/download-artifact@v3
        with:
          name: updated-config-files

      - name: Run integration tests
        uses: ./.github/workflows/test_frontend_integration_pipeline.yml
        with:
          command-install: 'mvn clean install -DskipTests'
          command-execute: 'mvn clean verify -D"environment=remote" -P"sample-test"'
          files-to-export: >
            target/site/serenity/serenity-summary.html
            target/logback-reports/logback-execution-report.txt
          prefix-team: 'automation-test-martianFlow'
          debug: false
          environment: 'main'
          path-report-file: 'target/serenity-reports/cucumber_report.json'
          repository: 'java-screenplay-browserstack-framework'
          target-url-zap: 'https://the-internet.herokuapp.com/'
          name-file-report: results.csv
        env:
          DIG_READER_GITHUB_ACCESS_TOKEN: ${{ secrets.DIG_READER_GITHUB_ACCESS_TOKEN }}
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}