name: test-integration-workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      cucumber-tag:
        description: 'Tag de cucumber a ejecutar'
        required: true
        default: '@RegRolRadicador' # Tag predeterminado
      browserstack-username:
        description: 'BrowserStack Username'
        required: true
      browserstack-access-key:
        description: 'BrowserStack Access Key'
        required: true

jobs:
  integration-e2e-tests:
    uses: ./.github/workflows/test_frontend_integration_pipeline.yml
    secrets:
      DIG_READER_GITHUB_ACCESS_TOKEN: ${{ secrets.DIG_READER_GITHUB_ACCESS_TOKEN }}

    with:
      command-install:  |
        sed -i 's/@buser@/'${{ github.event.inputs.browserstack-username }}'/' serenity.properties &&
        sed -i 's/@bkey@/'${{ github.event.inputs.browserstack-access-key }}'/' serenity.properties &&
        sed -i 's/@browserstack.user@/'${{ github.event.inputs.browserstack-username }}'/' browserstack.yml &&
        sed -i 's/@browserstack.key@/'${{ github.event.inputs.browserstack-access-key }}'/' browserstack.yml

      command-execute: 'mvn clean verify 
                        -D"environment=remote" 
                        -P"sample-test" 
                        -D"cucumber.filter.tags=${{ github.event.inputs.cucumber-tag }}"'
      files-to-export: >
        target/site/serenity/serenity-summary.html
        target/logback-reports/logback-execution-report.txt
      prefix-team: 'automation-test-martianFlow'
      debug: false
      environment: 'main'
      path-report-file: 'target/serenity-reports/cucumber_report.json'
      repository: 'java-screenplay-browserstack-framework'
      target-url-zap: 'https://the-internet.herokuapp.com/'
      name-file-report: results.csv
