name: automated-testing-integration
on:
  push:
    branches:
      -main
  workflow_dispatch:

jobs:
  integration-e2e-tests:
    uses: ./.github/workflows/test_frontend_integration.yml
    with:
      command-install: 'mvn clean install -DskipTests'
      command-execute: 'mvn clean verify -D"webdriver.driver=remote" -D"webdriver.remote.url=https://hub.browserstack.com/wd/hub" -P"sample-test"'
      files-to-export: >
        target/site/serenity/results.csv 
        target/site/serenity/index.html
      prefix-team: 'automation-test-martianFlow'
#      use-aws-credentials: false
      debug: false
      environment: 'main'
#      release-id-steward: ${{ inputs.release_id }}
      path-report-file: 'target/serenity-reports/cucumber_report.json'
#      test-plan-key: 'EYS-3194'
#      test-exec-key: 'EYS-4650'
      repository: 'java-screenplay-browserstack-framework'
      target-url-zap: 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'
      name-file-report: results.csv
    secrets:
      DIG_READER_GITHUB_ACCESS_TOKEN: ${{ secrets.DIG_READER_GITHUB_ACCESS_TOKEN }}
#      CLIENT_ID_XRAY: ${{ secrets.CLIENT_ID_XRAY }}
#      CLIENT_SECRET_XRAY: ${{ secrets.CLIENT_SECRET_XRAY }}


