name: update

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  integration-e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update serenity.properties with BrowserStack credentials
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        run: |
          echo "browserstack.user=${BROWSERSTACK_USERNAME}" >> serenity.properties
          echo "browserstack.key=${BROWSERSTACK_ACCESS_KEY}" >> serenity.properties
          echo "userName=${BROWSERSTACK_USERNAME}" >> browserstack.yml
          echo "accessKey=${BROWSERSTACK_ACCESS_KEY}" >> browserstack.yml
          cat serenity.properties
          cat browserstack.yml